/* news */
export const MARK_NEWS_AS_READ = 'MARK_NEWS_AS_READ'
export const DELETE_NEWS_ITEM  = 'DELETE_NEWS_ITEM'
export const LOAD_ALL_NEWS_START = 'LOAD_ALL_NEWS_START'
export const LOAD_ALL_NEWS_SUCCESS = 'LOAD_ALL_NEWS_SUCCESS'
export const LOAD_ALL_NEWS_FAIL = 'LOAD_ALL_NEWS_FAIL'

/* comments */
export const MARK_COMMENT_AS_READ = 'MARK_COMMENT_AS_READ'
export const POST_COMMENT = 'POST_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
